-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.accommodations
(
    id bigint NOT NULL DEFAULT nextval('accommodations_id_seq'::regclass),
    accommodation_standard character varying(255) COLLATE pg_catalog."default" NOT NULL,
    address character varying(255) COLLATE pg_catalog."default" NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    price bigint,
    sleeping_places_number bigint,
    CONSTRAINT accommodations_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.attractions
(
    id bigint NOT NULL DEFAULT nextval('attractions_id_seq'::regclass),
    address character varying(255) COLLATE pg_catalog."default" NOT NULL,
    description character varying(255) COLLATE pg_catalog."default",
    koszt bigint NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    season character varying(255) COLLATE pg_catalog."default" NOT NULL,
    price integer NOT NULL,
    CONSTRAINT attractions_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.attractions_guides
(
    attractions_id integer NOT NULL,
    guides_id integer NOT NULL,
    CONSTRAINT attractions_guides_pkey PRIMARY KEY (attractions_id, guides_id)
);

CREATE TABLE IF NOT EXISTS public.customers
(
    id bigint NOT NULL DEFAULT nextval('customers_id_seq'::regclass),
    address character varying(255) COLLATE pg_catalog."default" NOT NULL,
    date_of_birth date NOT NULL,
    is_deleted boolean,
    id_number character varying(255) COLLATE pg_catalog."default" NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    personal_number character varying(255) COLLATE pg_catalog."default" NOT NULL,
    phone_number character varying(255) COLLATE pg_catalog."default" NOT NULL,
    surename character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT customers_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.employees
(
    id bigint NOT NULL DEFAULT nextval('employees_id_seq'::regclass),
    address character varying(255) COLLATE pg_catalog."default" NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    phone_number character varying(255) COLLATE pg_catalog."default" NOT NULL,
    surename character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT employees_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.guides
(
    id bigint NOT NULL DEFAULT nextval('guides_id_seq'::regclass),
    address character varying(255) COLLATE pg_catalog."default" NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    phone_number character varying(255) COLLATE pg_catalog."default" NOT NULL,
    surename character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT guides_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.languages
(
    id bigint NOT NULL DEFAULT nextval('languages_id_seq'::regclass),
    code character varying(255) COLLATE pg_catalog."default" NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT languages_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.languages_employees
(
    languages_id integer NOT NULL,
    employees_id integer NOT NULL,
    CONSTRAINT languages_employees_pkey PRIMARY KEY (languages_id, employees_id)
);

CREATE TABLE IF NOT EXISTS public.languages_guides
(
    languages_id integer NOT NULL,
    guides_id integer NOT NULL,
    CONSTRAINT languages_guides_pkey PRIMARY KEY (languages_id, guides_id)
);

CREATE TABLE IF NOT EXISTS public.stages
(
    id bigint NOT NULL DEFAULT nextval('stages_id_seq'::regclass),
    end_date timestamp(6) without time zone NOT NULL,
    end_point character varying(255) COLLATE pg_catalog."default" NOT NULL,
    price bigint NOT NULL,
    start_date timestamp(6) without time zone NOT NULL,
    start_point character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT stages_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.transport_companys
(
    id bigint NOT NULL DEFAULT nextval('transport_companys_id_seq'::regclass),
    address character varying(255) COLLATE pg_catalog."default" NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    phone_number character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT transport_companys_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.transport_companys_transports
(
    transport_companies_id bigint NOT NULL,
    transports_id integer NOT NULL,
    CONSTRAINT transport_companys_transports_pkey PRIMARY KEY (transport_companies_id, transports_id)
);

CREATE TABLE IF NOT EXISTS public.transports
(
    id bigint NOT NULL DEFAULT nextval('transports_id_seq'::regclass),
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    seats_number bigint NOT NULL,
    units_number bigint NOT NULL,
    stage_id integer,
    CONSTRAINT transports_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.travels
(
    id bigint NOT NULL DEFAULT nextval('travels_id_seq'::regclass),
    description character varying(255) COLLATE pg_catalog."default",
    end_date timestamp(6) without time zone NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    price bigint NOT NULL,
    start_date timestamp(6) without time zone NOT NULL,
    CONSTRAINT travels_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.travels_accommodations
(
    travels_id bigint NOT NULL,
    accommodations_id bigint NOT NULL,
    CONSTRAINT travels_accommodations_pkey PRIMARY KEY (travels_id, accommodations_id)
);

CREATE TABLE IF NOT EXISTS public.travels_attractions
(
    travels_id bigint NOT NULL,
    attractions_id integer NOT NULL,
    CONSTRAINT travels_attractions_pkey PRIMARY KEY (travels_id, attractions_id)
);

CREATE TABLE IF NOT EXISTS public.travels_customers
(
    travels_id bigint NOT NULL,
    customers_id integer NOT NULL,
    CONSTRAINT travels_customers_pkey PRIMARY KEY (travels_id, customers_id)
);

CREATE TABLE IF NOT EXISTS public.travels_employees
(
    travels_id bigint NOT NULL,
    employees_id integer NOT NULL,
    CONSTRAINT travels_employees_pkey PRIMARY KEY (travels_id, employees_id)
);

CREATE TABLE IF NOT EXISTS public.travels_stages
(
    travels_id bigint NOT NULL,
    stages_id integer NOT NULL,
    CONSTRAINT travels_stages_pkey PRIMARY KEY (travels_id, stages_id)
);

ALTER TABLE IF EXISTS public.attractions_guides
    ADD CONSTRAINT fkba3aill11q6n05ny5kj7cvkrk FOREIGN KEY (attractions_id)
    REFERENCES public.attractions (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.attractions_guides
    ADD CONSTRAINT fki5ystoidee0geqpkwm6j1hrgm FOREIGN KEY (guides_id)
    REFERENCES public.guides (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.languages_employees
    ADD CONSTRAINT fkghv64y4d8mkpplugn22jmtpxx FOREIGN KEY (employees_id)
    REFERENCES public.employees (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.languages_employees
    ADD CONSTRAINT fkreed3vubrt7057m9vr6p3mblo FOREIGN KEY (languages_id)
    REFERENCES public.languages (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.languages_guides
    ADD CONSTRAINT fk7m7g4jdi8l3qe2r9gvwl0mr8j FOREIGN KEY (languages_id)
    REFERENCES public.languages (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.languages_guides
    ADD CONSTRAINT fkb1q73jfgi7epdns690y07deqw FOREIGN KEY (guides_id)
    REFERENCES public.guides (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.transport_companys_transports
    ADD CONSTRAINT fkhtj79l3uf0f23nh6wn84rxvrt FOREIGN KEY (transport_companies_id)
    REFERENCES public.transport_companys (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.transport_companys_transports
    ADD CONSTRAINT fkrsm2t8krrbso3ptndtp4q43mn FOREIGN KEY (transports_id)
    REFERENCES public.transports (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.transports
    ADD CONSTRAINT fkb4nriempuj35uimkpurmyj70e FOREIGN KEY (stage_id)
    REFERENCES public.stages (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.travels_accommodations
    ADD CONSTRAINT fk5qxi6u0uxsi9yi8rae3imgmrg FOREIGN KEY (travels_id)
    REFERENCES public.travels (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.travels_accommodations
    ADD CONSTRAINT fkae6m4i5xlhjjw3s69i0lctao1 FOREIGN KEY (accommodations_id)
    REFERENCES public.accommodations (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.travels_attractions
    ADD CONSTRAINT fkf0bgcxw1a73cjxyeerk9ssm33 FOREIGN KEY (travels_id)
    REFERENCES public.travels (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.travels_attractions
    ADD CONSTRAINT fkojheygx12f64dkc6sug6n8ybw FOREIGN KEY (attractions_id)
    REFERENCES public.attractions (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.travels_customers
    ADD CONSTRAINT fk7uxax71k2r3odt7mrh4rr2mc6 FOREIGN KEY (travels_id)
    REFERENCES public.travels (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.travels_customers
    ADD CONSTRAINT fknftu9xp9dc8555d7q0gkghvbv FOREIGN KEY (customers_id)
    REFERENCES public.customers (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.travels_employees
    ADD CONSTRAINT fk7dt3xf88m38bbj5pm8f1qkdov FOREIGN KEY (travels_id)
    REFERENCES public.travels (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.travels_employees
    ADD CONSTRAINT fkqp4lnpk48jj9whos1jpqcdg2t FOREIGN KEY (employees_id)
    REFERENCES public.employees (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.travels_stages
    ADD CONSTRAINT fk845l5m5xrfgeeayd5i1l2sik FOREIGN KEY (stages_id)
    REFERENCES public.stages (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.travels_stages
    ADD CONSTRAINT fkqpt9fufmdjhi0qq31jbxyeg9n FOREIGN KEY (travels_id)
    REFERENCES public.travels (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;